DROP TABLE IF EXISTS REDIRECTION;
CREATE TABLE REDIRECTION (
       ID SERIAL NOT NULL
     , USERNAME VARCHAR(45) NOT NULL
     , URL VARCHAR(256) NOT NULL
     , SHORT_URL VARCHAR(256) NOT NULL
     , REDIRECT_COUNT BIGINT DEFAULT 0
     , REDIRECT_CODE INTEGER DEFAULT 302
     , PRIMARY KEY (ID)
);
